---
- hosts: ansible-mgn
  become: yes
  become_user: root
  tasks:
  - name: Install NTP Server
    yum: name=ntp state=latest
  - name: IP
    lineinfile: path=/etc/ntp.conf regexp='^#restrict' line='restrict 192.168.100.0 mask 255.255.255.0 nomodify notrap'
  - name: IP server 0
    lineinfile: path=/etc/ntp.conf regexp='^server 0' line='server 2.th.pool.ntp.org iburst'
  - name: IP server 1
    lineinfile: path=/etc/ntp.conf regexp='^server 1' line='server 0.asia.pool.ntp.org iburst'
  - name: IP server 2
    lineinfile: path=/etc/ntp.conf regexp='^server 2' line='server 2.asia.pool.ntp.org iburst'
  - name: IP server 3
    lineinfile: path=/etc/ntp.conf regexp='^server 3' line=''
  - name: Install firewalld
    yum: name=firewalld state=latest
  - name: Start firewalld
    service: name=firewalld state=started
  - name: Open firewall
    firewalld: service=ntp permanent=yes state=enabled
  - name: Restart firewalld
    service: name=firewalld state=restarted
  - name: set timezone to Asia/Bangkok
    timezone: name=Asia/Bangkok
